### PR TITLE
Fixes Python3.6 and enum34

### PR DESCRIPTION
**Pull request by AndreMiras**
Module `enum34` should only be installed on Python < 3.4
Fixes host Python3 regression from ecd0bf6, the error was:
```
AttributeError: module 'enum' has no attribute 'IntFlag'
```

### CODE REVIEW

**Comment by AndreMiras** [comment]
I wish I could verify that in a unit test, but can't seem to reproduce that when running from tox. And it's bit overkill to write an integration test for it because it would require updating our CI to run also on host Python3 :confused: 
While we do want to do that at some point, it would make the suite run for even longer which we can't until we've addressed https://github.com/kivy/python-for-android/issues/1400

File: setup.py [hunk 1]
```diff
@@ -16,7 +16,8 @@
 data_files = []
 
 
-install_reqs = ['appdirs', 'colorama>=0.3.3', 'jinja2', 'six', 'enum34']
+install_reqs = ['appdirs', 'colorama>=0.3.3', 'jinja2', 'six',
+    'enum34;python_version<"3.4"']
```
Comment (inclement) [inline setup.py]: I would indent this further, but no need to have that hold up fixing the install.

Comment (AndreMiras) [reply setup.py]: True, well the linter (yes we have one :smile: ) didn't complain, but you're right I could have at least tried something like:
```
install_reqs = [
    'appdirs', 'colorama>=0.3.3', 'jinja2', 'six', 'enum34;python_version<"3.4"'
]
```
